__title__ = 'tes'
__description__ = 'Alfa Strakhovanie TES API Python SDK'
__url__ = ''
__version__ = '0.1.0'
__author__ = 'Sergey Popinevskiy'
__author_email__ = 'sergey.popinevskiy@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 Sergey Popinevskiy'
